QUERY_RESULT=`$SSH_CONN "$JOB_SCRIPT getPath $IMS_JOB_ID"`
IMS_INPUT_PATH=`echo $QUERY_RESULT | cut -d',' -f2`
IMS_OUTPUT_PATH=`echo $QUERY_RESULT | cut -d',' -f3`
PARENT_IMS_OUTPUT_PATH=`dirname $IMS_OUTPUT_PATH`
TACC_PATH=`echo $QUERY_RESULT | cut -d',' -f1`
$SCP_NO_PATH $TACC_PATH $IMS_ACCOUNT@$IMS_SERVER:$PARENT_IMS_OUTPUT_PATH/
$SSH_CONN "$JOB_SCRIPT update $IMS_JOB_ID finished"
